---
kind: pipeline
name: default

steps:
- name: build docker image
  image: plugins/docker
  settings:
    repo: svedrin/unifi-exporter
    tags: latest
    username: svedrin
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/unifi-exporter:latest"
  when:
    branch: master
    event:
      exclude:
      - pull_request
---
kind: signature
hmac: 8fce4a6b038b09b770fe984a8443c6fa53431049c2e57ac74989e1a484e1aea9

...
